dist: precise
language: csharp
solution: DeepGeo.sln
install:
  - nuget restore DeepGeo.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
mono:
  - latest
#before_script:
  # setup a virtual display so we can use forms, etc. 
  # - "export DISPLAY=:99.0"
  # - "sh -e /etc/init.d/xvfb start"
  # - sleep 3 # give xvfb some time to start
script:
  - xbuild /p:Configuration=Release DeepGeo.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./DeepGeo.Core.UnitTests/bin/Release/DeenGames.DeepGeo.Core.UnitTests.dll